config/routes.rb
Rails.application.routes.draw do
  resources :measurement_types

  devise_for :users
  resources :measurements
  post 'inputs', to: 'inputs#create'
  get 'profile', to: 'profile#show', as: 'show_profile'

  root 'measurements#index'

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
	belongs_to :user
	belongs_to :measurement_type
	validates_presence_of :measurement_type
	validates_presence_of :user
	validates_presence_of :value
end

app/models/measurement_type.rb
class MeasurementType < ActiveRecord::Base
	has_many :measurements
	validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
	before_action :authenticate_user!
	def create
		#TODO make atomic? create and move to model?
		# or maybe just put try and for loop
		# refactor !0 validation
		input = params[:input]
		datetime = Time.new(input['datetime(1i)'],input['datetime(2i)'],input['datetime(3i)'],input['datetime(4i)'],input['datetime(5i)'])
	    sugar = Measurement.new(datetime: datetime, value: input[:sugar].to_f, user: current_user, measurement_type_id: 1)
	    sugar.save if sugar.value != 0
	    insulin = Measurement.new(datetime: datetime, value: input[:insulin].to_f, user: current_user, measurement_type_id: 2)
	    insulin.save if insulin.value != 0
	    food = Measurement.new(datetime: datetime, value: input[:food].to_f, user: current_user, measurement_type_id: 3)
	    food.save if food.value != 0
		redirect_to show_profile_path
	end
end

app/controllers/measurement_types_controller.rb
class MeasurementTypesController < ApplicationController
  before_action :set_measurement_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @measurement_types = MeasurementType.all
    respond_with(@measurement_types)
  end

  def show
    respond_with(@measurement_type)
  end

  def new
    @measurement_type = MeasurementType.new
    respond_with(@measurement_type)
  end

  def edit
  end

  def create
    @measurement_type = MeasurementType.new(measurement_type_params)
    @measurement_type.save
    respond_with(@measurement_type)
  end

  def update
    @measurement_type.update(measurement_type_params)
    respond_with(@measurement_type)
  end

  def destroy
    @measurement_type.destroy
    respond_with(@measurement_type)
  end

  private
    def set_measurement_type
      @measurement_type = MeasurementType.find(params[:id])
    end

    def measurement_type_params
      params.require(:measurement_type).permit(:name)
    end
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  respond_to :html

  def index
    #TODO find another way to parse date from date_select ?
    date = params[:date]
    if date.present?
      @selected_day = Date.new(date['date(1i)'].to_i,date['date(2i)'].to_i,date['date(3i)'].to_i)
    else
      @selected_day = DateTime.current
    end
    @measurements = Measurement.where(datetime: @selected_day.beginning_of_day..@selected_day.end_of_day)
    respond_with(@measurements)
  end

  def show
    respond_with(@measurement)
  end

  def new
    @measurement = Measurement.new
    respond_with(@measurement)
  end

  def edit
  end

  def create
    @measurement = Measurement.new(measurement_params)
    @measurement.user = current_user
    @measurement.save
    #respond_with(@measurement)
    redirect_to show_profile_path
  end

  def update
    @measurement.update(measurement_params)
    respond_with(@measurement)
  end

  def destroy
    @measurement.destroy
    #respond_with(@measurement)
    redirect_to show_profile_path
  end

  private
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    def measurement_params
      params.require(:measurement).permit(:measurement_type_id, :datetime, :value)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	before_action :authenticate_user!
	def show
		#TODO find another way to parse date from date_select ?
		date = params[:date]
		if date.present?
		  @selected_day = Date.new(date['date(1i)'].to_i,date['date(2i)'].to_i,date['date(3i)'].to_i)
		else
		  @selected_day = DateTime.current
		end
		#TODO consider changing scope to from3am to 2:59 am
		@measurements = Measurement.where(datetime: @selected_day.beginning_of_day..@selected_day.end_of_day)
		@measurements_by_date = @measurements.group_by(&:datetime)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/input_helper.rb
module InputHelper
end

app/helpers/measurement_types_helper.rb
module MeasurementTypesHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-top-noradius">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">
      <%= image_tag 'logo_horizontal.png', class: 'logo-horizontal' %>
    </a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Homepage</a></li>
      <li><a href="https://github.com/kocasp/diabetes" target="_blank">View on GitHub <%= fa_icon "github-alt" %></a></li>
<!--       <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Home</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Dropdown header</li>
          <li><a href="#">Separated link</a></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li> -->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% unless user_signed_in?%>
      <%# TODO change to link_to method with class params %>
      <li><a href="<%= new_user_session_path %>">Log in</a></li>
      <li><a href="<%= new_user_registration_path %>">Sign up</a></li>
      <% end %>
      <li class="dropdown">
      	<% if user_signed_in?%>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profile <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="<%= show_profile_path %>">Profile details</a></li>
          <li class="divider"></li>
          <li><a data-method="delete" href="<%= destroy_user_session_path %>">Log out</a></li>
        </ul>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diabetes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://www.gstatic.com/swiffy/v7.1/runtime.js' %>


  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar.html.erb' %>

<%= yield %>

</body>
</html>

app/views/measurement_types/_form.html.erb
<%= form_for(@measurement_type) do |f| %>
  <% if @measurement_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement_type.errors.count, "error") %> prohibited this measurement_type from being saved:</h2>

      <ul>
      <% @measurement_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/measurement_types/edit.html.erb
<h1>Editing measurement_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @measurement_type %> |
<%= link_to 'Back', measurement_types_path %>

app/views/measurement_types/index.html.erb
<h1>Listing measurement_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measurement_types.each do |measurement_type| %>
      <tr>
        <td><%= measurement_type.name %></td>
        <td><%= link_to 'Show', measurement_type %></td>
        <td><%= link_to 'Edit', edit_measurement_type_path(measurement_type) %></td>
        <td><%= link_to 'Destroy', measurement_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measurement type', new_measurement_type_path %>

app/views/measurement_types/new.html.erb
<h1>New measurement_type</h1>

<%= render 'form' %>

<%= link_to 'Back', measurement_types_path %>

app/views/measurement_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @measurement_type.name %>
</p>

<%= link_to 'Edit', edit_measurement_type_path(@measurement_type) %> |
<%= link_to 'Back', measurement_types_path %>

app/views/measurements/_form.html.erb
<%= form_for(@measurement) do |f| %>
  <% if @measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% @measurement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :measurement_type_id %><br>
    <%= f.collection_select(:measurement_type_id, MeasurementType.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, :value => current_user.id ,:readonly => true %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<h1>Editing measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @measurement %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/index.html.erb
    <%# TODO move this to new view . Has nothing to do with measurements now %>
    <center style="background-color: #DBDADA;">
      <div id="drop_container" style="width: 800px; height: 410px; ">
      </div>
    </center>
<div class="row blue-stripe" >
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <a href="#" class="btn btn-default btn-lg btn-block register-button">Register For Free</a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7">
        <h1>Put your diabetes under control</h1>
        <p>
          Maecenas tristique sit amet mauris ut dictum. Aenean nec velit molestie, pretium orci sit amet, finibus dui. Mauris sollicitudin placerat lacus, porta sollicitudin mi faucibus sit amet. Nulla a porta lorem, a vulputate libero. Etiam justo arcu, iaculis vel egestas faucibus, gravida a tortor. Sed ac massa quis nisl pulvinar posuere vel vitae libero. Ut aliquam eu diam vel cursus. Aliquam vehicula sapien et nisl rutrum gravida sed quis purus. Suspendisse enim ligula, rhoncus eu nulla non, pulvinar imperdiet arcu. Phasellus rutrum diam ipsum, consequat elementum ipsum molestie at. Vivamus erat odio, tempor vitae magna eget, sollicitudin ullamcorper arcu. Nulla ut venenatis tellus. Sed non lorem dignissim, lacinia libero ac, dictum lacus. Nullam gravida purus quis elit ultricies iaculis.
        </p>
        <p>
          Aenean nec velit molestie, pretium orci sit amet, finibus dui. Mauris sollicitudin placerat lacus, porta sollicitudin mi faucibus sit amet. Nulla a porta lorem, a vulputate libero. Etiam justo arcu, iaculis vel egestas faucibus, gravida a tortor. Sed ac massa quis nisl pulvinar posuere vel vitae libero. Ut aliquam eu diam vel cursus. Aliquam vehicula sapien et nisl
        </p>
        <p>
          Pretium orci sit amet, finibus dui. Mauris sollicitudin placerat lacus, porta sollicitudin mi faucibus sit amet. Nulla a porta lorem, a vulputate libero. Etiam justo arcu, iaculis vel egestas faucibus, gravida a tortor. Sed ac massa quis nisl pulvinar posuere vel vitae libero. Ut aliquam eu diam vel cursus. Aliquam vehicula sapien et nisl
        </p>
        <p>
          <b>
            Mauris sollicitudin placerat lacus, porta sollicitudin mi faucibus sit amet. Nulla a porta lorem, a vulputate libero. Etiam justo arcu, iaculis vel egestas faucibus, gravida a tortor. Sed ac massa quis nisl pulvinar posuere vel vitae libero. Ut aliquam eu diam vel cursus. Aliquam vehicula sapien et nisl
          </b>
        </p>
      </div>
      <div class="col-md-1">
        <%= image_tag 'separator.png', style:"margin-top:100px" %>
      </div>
      <div class="col-md-4">
        <h1>Everything is free</h1>
        <p>
          Maecenas tristique sit amet mauris ut dictum. Aenean nec velit molestie, pretium orci sit amet, finibus dui. Mauris sollicitudin placerat lacus, porta sollicitudin mi faucibus sit amet. Nulla a porta lorem, a vulputate libero. 
        </p>
        <h1>Open source project</h1>
        <p>
          This software is licensed under an Open Source Initiative approved license. Maecenas tristique sit amet mauris ut dictum. Aenean nec velit molestie, pretium orci sit amet, finibus dui. Mauris sollicitudin placerat lacus, porta sollicitudin mi faucibus sit amet. Nulla a porta lorem, a vulputate libero. 
        </p>
        <h2>Developers, developers</h2>
        <p>
          Maecenas tristique sit amet mauris ut dictum. <b>GPL License</b> Aenean nec velit molestie, pretium orci sit amet, finibus dui. Mauris sollicitudin placerat lacus, porta sollicitudin mi faucibus sit amet. Nulla a porta lorem, a vulputate libero. 
        </p>
      </div>
    </div>
  </div>
</div>

<%# TODO invastigate data turbolinks true %>
<%# TODO fore swiffy js to load avery time. It is not working when hitting back or clicking link (turbolinks?) %>
<%= javascript_include_tag "banner" %>
<script>
  
  var stage = new swiffy.Stage(document.getElementById('drop_container'),
      swiffy_drop, {  });
  stage.start();
</script>

app/views/measurements/new.html.erb
<h1>New measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', measurements_path %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @measurement.measurement_type_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @measurement.user_id %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @measurement.datetime %>
</p>

<p>
  <strong>Value:</strong>
  <%= @measurement.value %>
</p>

<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>